/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev */

#include "el.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(RqHeader, RqHeader, AUTO)


PB_BIND(RsHeader, RsHeader, AUTO)


PB_BIND(CryptoInfo, CryptoInfo, AUTO)


PB_BIND(Rq, Rq, 2)


PB_BIND(TbrRegistration, TbrRegistration, AUTO)


PB_BIND(Aps, Aps, AUTO)


PB_BIND(Cell, Cell, AUTO)


PB_BIND(GsmCells, GsmCells, AUTO)


PB_BIND(UmtsCells, UmtsCells, AUTO)


PB_BIND(CdmaCells, CdmaCells, AUTO)


PB_BIND(LteCells, LteCells, AUTO)


PB_BIND(NbiotCells, NbiotCells, AUTO)


PB_BIND(Gnss, Gnss, AUTO)


PB_BIND(Rs, Rs, AUTO)


PB_BIND(ClientConfig, ClientConfig, AUTO)






/* On some platforms (such as AVR), double is really float.
 * Using double on these platforms is not directly supported
 * by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

/* @@protoc_insertion_point(eof) */
