CFLAGS = -Wall -Werror -Os -std=c99
LIB_DIR = ../bin
INCLUDES = -I. -I../libel
CLIENT_NAME = sample_client

CLIENT_SRCS = sample_client.c send.c config.c
CLIENT_OBJS = $(CLIENT_SRCS:.c=.o)

${CLIENT_NAME}: ${CLIENT_OBJS} ${LIB_DIR}/libel.a
	$(CC) -lc -lm -o ${CLIENT_NAME} ${CLIENT_OBJS} ${LIB_DIR}/libel.a

%.o: %.c
	$(CC) -c $(CFLAGS) ${INCLUDES} -o $@ $<

clean:
	rm -f *.o $(CLIENT_NAME) nv_cache_*
